config/routes.rb
Rails.application.routes.draw do
  resources :utenti
  resources :linea_ordini
  root 'vetrina#index', as: 'vetrina_index'
  resources :carrelli
  resources :prodotti
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/carrelli_controller.rb
class CarrelliController < ApplicationController
  before_action :set_carrello, only: [:show, :edit, :update, :destroy]

  # GET /carrelli
  # GET /carrelli.json
  def index
    @carrelli = Carrello.all
  end

  # GET /carrelli/1
  # GET /carrelli/1.json
  def show
  end

  # GET /carrelli/new
  def new
    @carrello = Carrello.new
  end

  # GET /carrelli/1/edit
  def edit
  end

  # POST /carrelli
  # POST /carrelli.json
  def create
    @carrello = Carrello.new(carrello_params)

    respond_to do |format|
      if @carrello.save
        format.html { redirect_to @carrello, notice: 'Carrello was successfully created.' }
        format.json { render :show, status: :created, location: @carrello }
      else
        format.html { render :new }
        format.json { render json: @carrello.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carrelli/1
  # PATCH/PUT /carrelli/1.json
  def update
    respond_to do |format|
      if @carrello.update(carrello_params)
        format.html { redirect_to @carrello, notice: 'Carrello was successfully updated.' }
        format.json { render :show, status: :ok, location: @carrello }
      else
        format.html { render :edit }
        format.json { render json: @carrello.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carrelli/1
  # DELETE /carrelli/1.json
  def destroy
    @carrello.destroy
    respond_to do |format|
      format.html { redirect_to carrelli_url, notice: 'Carrello was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_carrello
      @carrello = Carrello.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def carrello_params
      params.fetch(:carrello, {})
    end
end

app/helpers/carrelli_helper.rb
module CarrelliHelper
end

app/views/carrelli/_form.html.erb
<%= form_with(model: carrello, local: true) do |form| %>
  <% if carrello.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(carrello.errors.count, "error") %> prohibited this carrello from being saved:</h2>

      <ul>
        <% carrello.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carrelli/edit.html.erb
<h1>Editing Carrello</h1>

<%= render 'form', carrello: @carrello %>

<%= link_to 'Show', @carrello %> |
<%= link_to 'Back', carrelli_path %>

app/views/carrelli/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carrelli</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carrelli.each do |carrello| %>
      <tr>
        <td><%= link_to 'Show', carrello %></td>
        <td><%= link_to 'Edit', edit_carrello_path(carrello) %></td>
        <td><%= link_to 'Destroy', carrello, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Carrello', new_carrello_path %>

app/views/carrelli/new.html.erb
<h1>New Carrello</h1>

<%= render 'form', carrello: @carrello %>

<%= link_to 'Back', carrelli_path %>

app/views/carrelli/show.html.erb
<p id="notice"><%= notice %></p>

<h2> il tuo carrello </h2>

<table>
  <% @carrello.linea_ordini.each do |elemento| %>
    <tr>
      <td> <%= elemento.quantity %> &times </td>
      <td> <%= elemento.prodotto.nome %> </td>
      <td class=" prezzo elemento " > <%= number_to_currency(elemento.prezzo_totale) %></td>
    </tr>
  <% end %>
    <tr>
      <td> prezzo Totale : <%= @carrello.prezzo_ordine %></td>
    </tr>

</table>

<%= link_to 'Edit', edit_carrello_path(@carrello) %> |
<%= link_to 'Back', carrelli_path %>