config/routes.rb
Rails.application.routes.draw do
  resources :utenti
  resources :linea_ordini
  root 'vetrina#index', as: 'vetrina_index'
  resources :carrelli
  resources :prodotti
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/utenti_controller.rb
class UtentiController < ApplicationController
  before_action :set_utente, only: [:show, :edit, :update, :destroy]

  # GET /utenti
  # GET /utenti.json
  def index
    @utenti = Utente.all
  end

  # GET /utenti/1
  # GET /utenti/1.json
  def show
    @utente = Utente.find(params[:id])
  end

  # GET /utenti/new
  def new
    @utente = Utente.new
  end

  # GET /utenti/1/edit
  def edit
  end

  # POST /utenti
  # POST /utenti.json
  def create
    @utente = Utente.new(utente_params)

    respond_to do |format|
      if @utente.save
        format.html { redirect_to @utente, notice: 'Utente was successfully created.' }
        format.json { render :show, status: :created, location: @utente }
      else
        format.html { render :new }
        format.json { render json: @utente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /utenti/1
  # PATCH/PUT /utenti/1.json
  def update
    respond_to do |format|
      if @utente.update(utente_params)
        format.html { redirect_to @utente, notice: 'Utente was successfully updated.' }
        format.json { render :show, status: :ok, location: @utente }
      else
        format.html { render :edit }
        format.json { render json: @utente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /utenti/1
  # DELETE /utenti/1.json
  def destroy
    @utente.destroy
    respond_to do |format|
      format.html { redirect_to utenti_url, notice: 'Utente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_utente
      @utente = Utente.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def utente_params
      params.require(:utente).permit(:nome, :email, :password, :password_confirmation)
    end
end

app/helpers/utenti_helper.rb
module UtentiHelper
  def gravatar_for(utente)
    gravatar_id = Digest::MD5::hexdigest(utente.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: utente.nome, class: "gravatar")
  end
end

app/views/utenti/_form.html.erb
<%= form_with(model: utente, local: true) do |form| %>
  <% if utente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(utente.errors.count, "error") %> prohibited this utente from being saved:</h2>

      <ul>
        <% utente.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/utenti/edit.html.erb
<h1>Editing Utente</h1>

<%= render 'form', utente: @utente %>

<%= link_to 'Show', @utente %> |
<%= link_to 'Back', utenti_path %>

app/views/utenti/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Utenti</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @utenti.each do |utente| %>
      <tr>
        <td><%= utente.nome %></td>
        <td><%= utente.email %></td>
        <td><%= link_to 'Show', utente %></td>
        <td><%= link_to 'Edit', edit_utente_path(utente) %></td>
        <td><%= link_to 'Destroy', utente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Utente', new_utente_path %>

app/views/utenti/new.html.erb
<h1>New Utente</h1>

<%= render 'form', utente: @utente %>

<%= link_to 'Back', utenti_path %>

app/views/utenti/show.html.erb
<p id="notice"><%= notice %></p>

<% provide(:title, @utente.nome) %>
<h1>
  <%= gravatar_for @utente %>
  <%= @utente.nome %>
</h1>


<p>
  <strong>Nome:</strong>
  <%= @utente.nome %>
</p>

<p>
  <strong>Email:</strong>
  <%= @utente.email %>
</p>

<%= link_to 'Edit', edit_utente_path(@utente) %> |
<%= link_to 'Back', utenti_path %>