config/routes.rb
Rails.application.routes.draw do
  resources :utenti
  resources :linea_ordini
  root 'vetrina#index', as: 'vetrina_index'
  resources :carrelli
  resources :prodotti
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/linea_ordini_controller.rb
class LineaOrdiniController < ApplicationController
  include CarrelloCorrente
  before_action :set_carrello, only: [:create]
  before_action :set_linea_ordine, only: [:show, :edit, :update, :destroy]

  # GET /linea_ordini
  # GET /linea_ordini.json
  def index
    @linea_ordini = LineaOrdine.all
  end

  # GET /linea_ordini/1
  # GET /linea_ordini/1.json
  def show
  end

  # GET /linea_ordini/new
  def new
    @linea_ordine = LineaOrdine.new
  end

  # GET /linea_ordini/1/edit
  def edit
  end

  # POST /linea_ordini
  # POST /linea_ordini.json
  def create
    prodotto = Prodotto.find(params[:prodotto_id])
    @linea_ordine = @carrello.addProdotto(prodotto)

    respond_to do |format|
      if @linea_ordine.save
        format.html { redirect_to @linea_ordine.prodotto, notice: 'Linea ordine was successfully created.' }
        format.json { render :show, status: :created, location: @linea_ordine }
      else
        format.html { render :new}
        format.json { render json: @linea_ordine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /linea_ordini/1
  # PATCH/PUT /linea_ordini/1.json
  def update
    respond_to do |format|
      if @linea_ordine.update(linea_ordine_params)
        format.html { redirect_to @linea_ordine, notice: 'Linea ordine was successfully updated.' }
        format.json { render :show, status: :ok, location: @linea_ordine }
      else
        format.html { render :edit }
        format.json { render json: @linea_ordine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /linea_ordini/1
  # DELETE /linea_ordini/1.json
  def destroy
    @linea_ordine.destroy
    respond_to do |format|
      format.html { redirect_to linea_ordini_url, notice: 'Linea ordine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_linea_ordine
      @linea_ordine = LineaOrdine.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def linea_ordine_params
      params.require(:linea_ordine).permit(:prodotto_id, :carrello_id)
    end
end

app/helpers/linea_ordini_helper.rb
module LineaOrdiniHelper
end

app/views/linea_ordini/_form.html.erb
<%= form_with(model: linea_ordine, local: true) do |form| %>
  <% if linea_ordine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(linea_ordine.errors.count, "error") %> prohibited this linea_ordine from being saved:</h2>

      <ul>
        <% linea_ordine.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :prodotto_id %>
    <%= form.text_field :prodotto_id %>
  </div>

  <div class="field">
    <%= form.label :carrello_id %>
    <%= form.text_field :carrello_id %>
  </div>

  <div class="field">
    <%= form.label :quantita %>
    <%= form.text_field :quantita %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/linea_ordini/edit.html.erb
<h1>Editing Linea Ordine</h1>

<%= render 'form', linea_ordine: @linea_ordine %>

<%= link_to 'Show', @linea_ordine %> |
<%= link_to 'Back', linea_ordini_path %>

app/views/linea_ordini/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Linea Ordini</h1>

<table>
  <thead>
    <tr>
      <th>| Prodotto |</th>
      <th>| Carrello | </th>
      <th>| Quantità |</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @linea_ordini.each do |linea_ordine| %>
      <tr>
        <td><%= linea_ordine.prodotto_id %></td>
        <td><%= linea_ordine.carrello_id %></td>
        <td><%= linea_ordine.quantity %> </td>
        <td><%= link_to 'Show', linea_ordine %></td>
        <td><%= link_to 'Edit', edit_linea_ordine_path(linea_ordine) %></td>
        <td><%= link_to 'Destroy', linea_ordine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Linea Ordine', new_linea_ordine_path %>

app/views/linea_ordini/new.html.erb
<h1>New Linea Ordine</h1>

<%= render 'form', linea_ordine: @linea_ordine %>

<%= link_to 'Back', linea_ordini_path %>

app/views/linea_ordini/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Prodotto:</strong>
  <%= @linea_ordine.prodotto_id %>
</p>

<p>
  <strong>Carrello:</strong>
  <%= @linea_ordine.carrello_id %>
</p>

<%= link_to 'Edit', edit_linea_ordine_path(@linea_ordine) %> |
<%= link_to 'Back', linea_ordini_path %>