config/routes.rb
Rails.application.routes.draw do
  resources :utenti
  resources :linea_ordini
  root 'vetrina#index', as: 'vetrina_index'
  resources :carrelli
  resources :prodotti
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/prodotti_controller.rb
class ProdottiController < ApplicationController
  before_action :set_prodotto, only: [:show, :edit, :update, :destroy]

  # GET /prodotti
  # GET /prodotti.json
  def index
    @prodotti = Prodotto.all
  end

  # GET /prodotti/1
  # GET /prodotti/1.json
  def show
  end

  # GET /prodotti/new
  def new
    @prodotto = Prodotto.new
  end

  # GET /prodotti/1/edit
  def edit
  end

  # POST /prodotti
  # POST /prodotti.json
  def create
    @prodotto = Prodotto.new(prodotto_params)

    respond_to do |format|
      if @prodotto.save
        format.html { redirect_to @prodotto, notice: 'Prodotto was successfully created.' }
        format.json { render :show, status: :created, location: @prodotto }
      else
        format.html { render :new }
        format.json { render json: @prodotto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prodotti/1
  # PATCH/PUT /prodotti/1.json
  def update
    respond_to do |format|
      if @prodotto.update(prodotto_params)
        format.html { redirect_to @prodotto, notice: 'Prodotto was successfully updated.' }
        format.json { render :show, status: :ok, location: @prodotto }
      else
        format.html { render :edit }
        format.json { render json: @prodotto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prodotti/1
  # DELETE /prodotti/1.json
  def destroy
    @prodotto.destroy
    respond_to do |format|
      format.html { redirect_to prodotti_url, notice: 'Prodotto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prodotto
      @prodotto = Prodotto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def prodotto_params
      params.require(:prodotto).permit(:nome, :prezzo, :descrizione)
    end
end

app/helpers/prodotti_helper.rb
module ProdottiHelper
end

app/views/prodotti/_form.html.erb
<%= form_with(model: prodotto, local: true) do |form| %>
  <% if prodotto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(prodotto.errors.count, "error") %> prohibited this prodotto from being saved:</h2>

      <ul>
        <% prodotto.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :prezzo %>
    <%= form.text_field :prezzo %>
  </div>

  <div class="field">
    <%= form.label :descrizione %>
    <%= form.text_field :descrizione %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/prodotti/edit.html.erb
<h1>Editing Prodotto</h1>

<%= render 'form', prodotto: @prodotto %>

<%= link_to 'Show', @prodotto %> |
<%= link_to 'Back', prodotti_path %>

app/views/prodotti/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Prodotti</h1>
<p> aggiungi/modifica prodotti</p>
<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Prezzo</th>
      <th>Descrizione</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prodotti.each do |prodotto| %>
      <tr>
        <td><%= prodotto.nome %></td>
        <td><%= prodotto.prezzo %></td>
        <td><%= prodotto.descrizione %></td>
        <td><%= link_to 'Show', prodotto %></td>
        <td><%= link_to 'Edit', edit_prodotto_path(prodotto) %></td>
        <td><%= link_to 'Destroy', prodotto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Prodotto', new_prodotto_path %>

app/views/prodotti/new.html.erb
<h1>New Prodotto</h1>

<%= render 'form', prodotto: @prodotto %>

<%= link_to 'Back', prodotti_path %>

app/views/prodotti/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @prodotto.nome %>
</p>

<p>
  <strong>Prezzo:</strong>
  <%= @prodotto.prezzo %>
</p>

<p>
  <strong>Descrizione:</strong>
  <%= @prodotto.descrizione %>
</p>

<%= link_to 'Edit', edit_prodotto_path(@prodotto) %> |
<%= link_to 'Back', prodotti_path %>